development:
  bucket_name: surferbreak-development
  access_key_id: 13WQ80HKRY1EJA7SH9R2
  secret_access_key: 67IJS5Tc8VQLrrougD2AJQBFyw3B2YER6dAHXvwj

test:
  bucket_name: test_bucket
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: surferbreak
  access_key_id: 
  secret_access_key: 
